import Store1 from "../../../assets/store1.webp";
import Store2 from "../../../assets/store2.webp";
import Store3 from "../../../assets/store3.webp";
import Store4 from "../../../assets/store4.webp";
import Store5 from "../../../assets/store5.webp";
import Store6 from "../../../assets/store6.webp";
import Store7 from "../../../assets/store7.webp";
import Store8 from "../../../assets/store8.webp";
import Store9 from "../../../assets/store9.webp";
import Store10 from "../../../assets/store10.webp";
import Store11 from "../../../assets/store11.webp";
import Store12 from "../../../assets/store12.webp";
import Store13 from "../../../assets/store13.webp";
import Store14 from "../../../assets/store14.webp";
import Store15 from "../../../assets/store15.webp";
import Store16 from "../../../assets/store16.webp";
import Store17 from "../../../assets/store17.webp";
import Store18 from "../../../assets/store18.webp";
import Store19 from "../../../assets/store19.webp";
import Store20 from "../../../assets/store20.webp";
import Store21 from "../../../assets/store21.webp";
import Store22 from "../../../assets/store22.webp";
import Store23 from "../../../assets/store23.webp";
import Store24 from "../../../assets/store24.webp";
import Store25 from "../../../assets/store25.webp";
import Store26 from "../../../assets/store26.webp";
import Store27 from "../../../assets/store27.webp";
import Store28 from "../../../assets/store28.webp";
import Store29 from "../../../assets/store29.webp";
import Store30 from "../../../assets/store30.webp";
import Store31 from "../../../assets/store31.webp";
import Store32 from "../../../assets/store32.webp";

let CardData3 = [
  {
    id: "t1",
    img: Store1,
    title: "High Protein Dark Chocolate Peanut Butter",
    price: 379,
    delprice: 399,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t2",
    img: Store2,
    title: "All Natural Peanut Butter",
    price: 166,
    delprice: 175,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t3",
    img: Store3,
    title: "High Protein Dark Chocolate Oats",
    price: 150,
    delprice: 199,
    opt: "400g",
    opt1: "1kg",
    quantity: 1,
  },
  {
    id: "t4",
    img: Store4,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "400g",
    opt1: "1kg",
    quantity: 1,
  },
  {
    id: "t5",
    img: Store5,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t6",
    img: Store6,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t7",
    img: Store7,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t8",
    img: Store8,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t9",
    img: Store9,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t10",
    img: Store10,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t11",
    img: Store11,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t12",
    img: Store12,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t13",
    img: Store13,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t14",
    img: Store14,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t15",
    img: Store15,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t16",
    img: Store16,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t17",
    img: Store17,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t18",
    img: Store18,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t19",
    img: Store19,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t20",
    img: Store20,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t21",
    img: Store21,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t22",
    img: Store22,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t23",
    img: Store23,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t24",
    img: Store24,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t25",
    img: Store25,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t26",
    img: Store26,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t27",
    img: Store27,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t28",
    img: Store28,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t29",
    img: Store29,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t30",
    img: Store30,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t31",
    img: Store31,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
  {
    id: "t32",
    img: Store32,
    title: "Organic Wholegrain Brown Rice Cakes",
    price: 152,
    delprice: 160,
    opt: "350g",
    opt1: "800g",
    quantity: 1,
  },
];
export default CardData3;
